add typescript readme example
fastify/fastify-error pull request #105
Opened 2023-05-27 23:01 UTC by trim21

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-06-01 08:52 UTC, Uzlopak commented
@Fdawgs Can you review the language?

2023-06-01 15:04 UTC, Fdawgs requested changes

2023-06-01 15:04 UTC, Fdawgs commented on README.md
> +It's possible to limit your error constructor with TypeScript generic type:
```suggestion
It is possible to limit your error constructor with a generic type using TypeScript:
```

2023-06-02 04:56 UTC, Fdawgs approved these changes

2023-06-02 04:56 UTC, merged

2023-06-03 02:13 UTC, trim21 commented
Can we have a new npm release?

2023-06-03 06:16 UTC, climba03003 commented
Released