Fix type of base argument create error
fastify/fastify-error pull request #108
Opened 2023-06-08 05:32 UTC by jessta

This PR fixes the type of the Base argument to createError.

The previous type was Error which is the type of an Error value, but it's being used is as a constructor for a class that inherits from Error.

This change makes the type of Base a constructor for a class that inherits from Error so it's type matches it's usage and  documented examples.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-06-08 05:44 UTC, climba03003 requested changes
Please use `ErrorConstructor` if you really means to be a constructor.

2023-06-20 01:13 UTC, jessta commented
> Please use `ErrorConstructor` if you really means to be a constructor.

`new () => Error` is a subset of `ErrorConstructor` and provides all the functionality required by createError().
It doesn't seem necessary to also require that these classes are also callable as functions.

I'd like to be able to use this with classes that inherit from Error, which aren't callable as functions like `ErrorConstructor` requires.
eg.
class MyError extends Error {}

2023-06-21 11:39 UTC, jsumners commented
I'm having difficulty following the reasoning for this PR, but it sounds like a misunderstanding of `Error`. The implementation here follows the specification:

https://262.ecma-international.org/13.0/#sec-error-objects
> creates and initializes a new Error object when called as a function rather than as a [constructor](https://262.ecma-international.org/13.0/#constructor). Thus the function call `Error(…)` is equivalent to the object creation expression `new Error(…)` with the same arguments.

2023-06-21 14:57 UTC, jessta commented
@jsumners The value `Error` has the type `ErrorConstructor`, you can call `Error` as a function eg. Error("some string") or using `new Error("some string")` and you''ll get a value of type `Error`.

The current types defined for `createError` only allow you to pass a value of type `Error` as the `Base` parameter, but the function only works if you pass a value of `ErrorConstructor`. In fact ,the default value assigned to `Base` is `Error` which has the type `ErrorConstructor`.

This PR makes it possible to call `createError('CODE', 'hey %s', 500, Error)` from Typescript, without this change you can only call `createError('CODE', 'hey %s', 500, Error("some string"))` which results in a runtime error.

Without this change it's not possible to call createError() correctly from Typescript.

2023-06-22 11:52 UTC, jsumners commented
ping: @fastify/typescript

2023-06-26 17:50 UTC, climba03003 commented
`ErrorConstructor` is a proper Error structure for JavaScript. 
And it also required to provide the `function` creation method.

```ts
interface ErrorConstructor {
    new(message?: string): Error;
    (message?: string): Error;
    readonly prototype: Error;
}
```

But, I still in favor of using `ErrorConstructor` as it is more predictable in the structure and follow the spec.

2023-06-27 07:49 UTC, fox1t commented
As @Uzlopak said, this is a TS definition issue. Thanks for finding and fixing it, @jessta!
I agree with @climba03003, and I would prefer `ErrorConstructor` to be used here since it is more flexible and usable by `Object.create(`.
@jessta I am trying to understand why you would prefer to have only a strict constructor here.

2023-06-29 03:25 UTC, jessta commented
I've updated the types to be ErrorConstructor since that seems to be the consensus.

2023-06-29 05:44 UTC, Uzlopak approved these changes
LGTM

2023-06-29 07:06 UTC, climba03003 approved these changes

2023-06-29 07:07 UTC, merged