fix: migrate from tap to node test and c8
fastify/fastify-error pull request #130
Opened 2024-08-01 01:18 UTC by dancastillo

#### Checklist

Closes #129 

This PR migrates from `tap` to `node:test` and `c8`

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-08-01 03:33 UTC, climba03003 requested changes

2024-08-01 10:52 UTC, jsumners commented on test/index.test.js
> +test('Create error with zero parameter', (t) => {
You cannot use `t.assert` as it is not available in Node.js 18 or 20.

2024-08-01 10:54 UTC, jsumners commented on test/index.test.js
> +const { test } = require('node:test')
```suggestion
const test = require('node:test')
```

2024-08-01 13:07 UTC, climba03003 commented on test/index.test.js
> +test('Create error with zero parameter', (t) => {
It is available on node@20, but not node@18.
That's why I request to update using v5 workflow

2024-08-01 13:09 UTC, climba03003 commented on test/index.test.js
> +test('Create error with zero parameter', (t) => {
See https://github.com/nodejs/node/releases/tag/v20.15.0

2024-08-03 18:05 UTC, climba03003 requested changes

2024-08-03 18:05 UTC, climba03003 commented on test/index.test.js
> +  t.plan(6)
```suggestion
  t.plan(7)
```

2024-08-03 18:24 UTC, dancastillo commented on test/index.test.js
> +  t.plan(6)
Should be fixed now

2024-08-05 22:13 UTC, jsumners approved these changes

2024-08-06 03:00 UTC, climba03003 approved these changes

2024-08-06 03:00 UTC, merged

2024-08-06 06:22 UTC, gurgunday commented
Thank you @dancastillo!